### ISSUE TITLE
Sketch 3.4

### ISSUE THREAD

**Issue by mischugo** [abynim/sketchy-pies#1]
Hello,
it seems, your great plug in does not woks with SketchApp 3.4

And, by the way, what du you think about  a bar chart like creating a rectangle and then settings the colors and space and values for each :-)

Thanks!

**Comment by shanecarmody** [comment]
@mischugo I’m using Sketch 3.4.2 and it’s working perfectly. What issues are you having? Maybe I can help you out.

**Comment by mischugo** [comment]
I have download and installed again. Now it woks.
Before i got the selected circle many times over itself, with different colors.
But not as parts of the circle.
So, may be there was installation issue (?)

It would be cool to have the option for percentage settings, and of course, bar and line chart creation :-)

Thanks a lot *

**Comment by shanecarmody** [comment]
> It would be cool to have the option for percentage settings, and of course, bar and line chart creation :-)

You could modify the plugin so that when you choose `Plugins > Sketchy Pies > Convert to Pie Chart` you are prompted to enter a percentage along with a colour e.g.

`(#161032, 20%),(#FAFF81, 20%),(#FFC53A, 20%),(#E06D06, 20%),(#B26700, 20%)`

<img width="469" alt="screen shot 2015-11-27 at 22 41 27" src="https://cloud.githubusercontent.com/assets/433990/11448426/4e48229a-9558-11e5-8f7c-f05cad8f2a6a.png">

This way you could take the percentage inputted by the user and multiply it by 360 to get the `Rotate` value (in this case 20% is 0.2 when we multiply so: 0.2 \* 360 = 72). 

<img width="195" alt="screen shot 2015-11-27 at 22 49 28" src="https://cloud.githubusercontent.com/assets/433990/11448458/27abc212-9559-11e5-8d64-88425434b4fa.png">

That’s my **very** basic suggestion anyway. I’m not really familiar with CocoaScript so I won’t attempt to implement it :smile: @abynim would you know how to implement that?

**Comment by abynim** [comment]
Added feature for percent-based pie charts. Thanks @shanecarmody for the suggestion.

**Comment by shanecarmody** [comment]
Nice! Thank you.

Le mar. 13 sept. 2016 08:24, Aby Nimbalkar notifications@github.com a
écrit :
